# 1. k: v # k v之间是空格区分
# 2. 属性有层级关系，使用下一行，空两格空格
# 3. 左侧对齐的代表同一层级的属性

server:
  port: 9999

spring:
  servlet:
    multipart:
      max-file-size: 10MB
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: aaa

person:
  name: 张三
  age: 18
  birthday: 2010/10/10 12:12:12
  like: true
  child:
    name: 李四
    age: 20
    birthday: 2018/10/10
#    text: ["abc", "def"]
    text:
      - abc
      - def
  dogs:
    - name: 小黑
      age: 3
    - name: 小白
      age: 4
  cats:
    c1:
      name: 小蓝
      age: 2
    c2: {name: 小绿, age: 2} # 对象也可以用{}表示
